# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: grab
  joint_model_group_pose: grab standby
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_link__link_1
    - link_1__link_2
    - link_2__link_3
    - link_3__link_4
    - link_4__link_5
    - base_link__link_11
    - link_11__link_22
    - link_22__link_33
    - link_33__link_44
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []