# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link__link_1
  pid: {p: 2000.0, i: 100, d: 500.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_2__link_3
  pid: {p: 50000.0, i: 100, d: 2000.0}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link__link_11
  pid: {p: 2000.0, i: 100, d: 500.0}
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_11__link_22
  pid: {p: 2000.0, i: 100, d: 500.0}
joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_22__link_33
  pid: {p: 2000.0, i: 100, d: 500.0}
joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_33__link_44
  pid: {p: 2000.0, i: 100, d: 500.0}